#!/bin/bash

BRANCH_NAME=$(git branch --show-current)
BRANCH_NAME="${BRANCH_NAME##*/}"

JIRA_ISSUE_KEY=$(echo "$BRANCH_NAME" | egrep -o 'TRA-[0-9]+')

COMMIT_MSG_FILE=$1

BRANCH_IN_COMMIT=$(grep -c "\\[$JIRA_ISSUE_KEY\\]" "$COMMIT_MSG_FILE")

if [ -n "$JIRA_ISSUE_KEY" ] && [ "$BRANCH_IN_COMMIT" -eq 0 ]; then
  sed -i.bak -e "1s/^/[$JIRA_ISSUE_KEY] /" "$COMMIT_MSG_FILE"
fi