name: '🐛 Bug'
description: '버그 수정. 생성 시 Jira Task와 fix/TRA-... 브랜치가 자동 생성됩니다.'
title: '[fix] '
labels: [bug]
body:
  - type: textarea
    id: condition
    attributes:
      label: '🕵️ Condition'
      description: '버그가 발생한 상황/조건을 적어주세요'
      placeholder: '에러 발생 조건 및 대상'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: '📝 Description'
      description: '에러 발생 상황을 설명해주세요'
      placeholder: '에러 발생 상황 설명'
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: '✅ To Do List'
      description: 'PR 날릴 때 모두 체크되어야 합니다'
      value: |
        - [ ] 수정1
        - [ ] 수정2
  - type: textarea
    id: etc
    attributes:
      label: '📚 Etc'
      description: '작업 중 특이사항이 있으면 적어주세요'